# Generated by Django 3.0.8 on 2020-07-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_auto_20200724_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='codigo',
            field=models.CharField(default='', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
